// 置顶数据
export const sticks = [
  {
    pid: 2,
    categoryId: 2,
    title: '木瓜移动是一家深耕全球市场十二年的互联网海外营销公司，早已深知全球的文化和海外消费者的喜好。木瓜移动为出海企业提供到位的本地化策略，让当地用户感到产品就是为他们...',
  },
  {
    pid: 3,
    categoryId: 7,
    title: '马达加斯加将建全球首所3D打印学校',
  },
  {
    pid: 13,
    categoryId: 6,
    title: '在此次发布会上，航天科技集团宇航部部长林益明介绍了全年科研生产任务呈现三大特点：一是发射和飞行试验次数再创新高。航天科技今年计划安排40余此发射任务，发射80余...',
  },
  {
    pid: 64,
    categoryId: 8,
    title: '<img style="display:inline-block;vertical-align:top" src="http://dev.discuz.com/emoji/qq/ciya.gif" alt="ciya" class="qq-emotion"><img style="display:inline-block;vertical-align:top" src="http://dev.discuz.com/emoji/qq/se.gif" alt="ciya" class="qq-emotion"> <span id="member" value="4">@a3</span>  <span id="topic" value="3">#消费者315#</span> 记者从最高人民检察院获悉，文化和旅游部原党组副书记、副部长李金早涉嫌受贿一案，由国家监察委员会调查终结，经最高...',
  },
];

// 分类数据
export const categories = [
  {
    pid: 1,
    name: '北京市',
    description: '北京市',
    icon: '',
    sort: 0,
    property: 0,
    threadCount: 31,
    parentid: 0,
    canCreateThread: true,
    searchIds: [
      1,
      5,
      6,
      7,
      8,
    ],
    children: [
      {
        pid: 5,
        name: '东城区',
        description: '东城区',
        icon: '',
        sort: 1,
        property: 0,
        threadCount: 7,
        parentid: 1,
        canCreateThread: false,
        searchIds: 5,
      },
      {
        pid: 6,
        name: '西城区',
        description: '西城区',
        icon: '',
        sort: 2,
        property: 0,
        threadCount: 14,
        parentid: 1,
        canCreateThread: false,
        searchIds: 6,
      },
      {
        pid: 7,
        name: '海淀区',
        description: '海淀区',
        icon: '',
        sort: 3,
        property: 0,
        threadCount: 5,
        parentid: 1,
        canCreateThread: true,
        searchIds: 7,
      },
      {
        pid: 8,
        name: '朝阳区',
        description: '朝阳区',
        icon: '',
        sort: 4,
        property: 0,
        threadCount: 5,
        parentid: 1,
        canCreateThread: false,
        searchIds: 8,
      },
    ],
  },
  {
    pid: 2,
    name: '广州市',
    description: '广州市1',
    icon: '',
    sort: 1,
    property: 0,
    threadCount: 11,
    parentid: 0,
    canCreateThread: false,
    searchIds: [
      2,
      9,
      10,
    ],
    children: [
      {
        pid: 9,
        name: 'aaa',
        description: 'aaaaaaaaa',
        icon: '',
        sort: 1,
        property: 0,
        threadCount: 0,
        parentid: 2,
        canCreateThread: false,
        searchIds: 9,
      },
      {
        pid: 10,
        name: 'bbb',
        description: 'bbbbbbbb',
        icon: '',
        sort: 2,
        property: 0,
        threadCount: 0,
        parentid: 2,
        canCreateThread: false,
        searchIds: 10,
      },
    ],
  },
  {
    pid: 3,
    name: '深圳市',
    description: '深圳市1',
    icon: '',
    sort: 2,
    property: 0,
    threadCount: 9,
    parentid: 0,
    canCreateThread: false,
    searchIds: [
      3,
      11,
      12,
    ],
    children: [
      {
        pid: 11,
        name: '龙华区',
        description: '龙华区龙华区龙华区',
        icon: '',
        sort: 1,
        property: 0,
        threadCount: 2,
        parentid: 3,
        canCreateThread: false,
        searchIds: 11,
      },
      {
        pid: 12,
        name: '南山区',
        description: '南山区南山区南山区南山区',
        icon: '',
        sort: 2,
        property: 0,
        threadCount: 0,
        parentid: 3,
        canCreateThread: false,
        searchIds: 12,
      },
    ],
  },
  {
    pid: 4,
    name: '上海市',
    description: '上海市1',
    icon: '',
    sort: 3,
    property: 0,
    threadCount: 6,
    parentid: 0,
    canCreateThread: false,
    searchIds: 4,
    children: [],
  },
];

// 帖子数据
export const threads = {
  pageData: [
    {
      threadId: 142,
      textCover: false,
      userId: 30,
      categoryId: 12,
      title: '荣耀Play4T手机 【华为手机 店内可选】 极光色 全网通 (6+128G)888',
      price: '0.00',
      attachmentPrice: '0.00',
      isEssence: false,
      user: {
        userId: 30,
        userName: 'a46',
        avatar: 'http://dev.discuz.com/storage/avatars/000/00/00/30.png?1618384809',
        threadCount: 30,
        followCount: 0,
        fansCount: 0,
        likedCount: 8,
        questionCount: 0,
        isRealName: false,
        joinedAt: '2021-04-01 11:21:26',
      },
      group: {
        groupId: 16,
        groupName: '入门会员',
        groupIcon: '',
        isDisplay: true,
      },
      likeReward: {
        users: [],
        likePayCount: 0,
        shareCount: 0,
      },
      position: {
        longitude: '0.0000000',
        latitude: '0.0000000',
        address: '',
        location: '',
      },
      content: {
        text: '去年11月以来，中国海关总署宣布，因从澳大利亚多地进口的原木中检出检疫性有害生物，根据相关法律暂停',
        indexes: {
          $0: {
            tomId: '101',
            operation: 'select',
            body: [
              {
                id: 178,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                attachment: '5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                extension: 'jpg',
                fileName: '12.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 55544,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv_thumb.jpg',
              },
              {
                id: 179,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                attachment: '8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                extension: 'jpg',
                fileName: '14.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 28693,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2_thumb.jpg',
              },
              {
                id: 180,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                attachment: 'FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                extension: 'jpg',
                fileName: '13.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 13760,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l_thumb.jpg',
              },
              {
                id: 181,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                attachment: 'GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                extension: 'jpg',
                fileName: '15.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 37923,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ_thumb.jpg',
              },
            ],
            threadId: 142,
          },
          $1: {
            tomId: '103',
            operation: 'select',
            body: false,
            threadId: 142,
          },
          $2: {
            tomId: '102',
            operation: 'select',
            body: false,
            threadId: 142,
          },
          $3: {
            tomId: '104',
            operation: 'select',
            body: {
              userId: 30,
              platformId: '69777843625',
              title: '卓真 全网通平板电脑11.6英寸10G+128G安卓手机5G学生平板二合一科大讯飞语音学习机Y105 香槟金【10G+128G】+3年质保 全网通+WIFI版',
              imagePath: 'https://m.360buyimg.com/mobilecms/s750x750_jfs/t1/170438/16/18737/492481/607836ffE979ae457/4568e0cda3b32d79.jpg!q80.dpg',
              price: '939.00',
              type: 2,
              typeName: '京东',
              readyContent: 'https://item.jd.com/69777843625.html',
              detailCcontent: 'https://item.m.jd.com/product/69777843625.html',
            },
            threadId: 142,
          },
          $4: {
            tomId: '108',
            operation: 'select',
            body: [
              {
                id: 182,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                attachment: 'NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                extension: 'zip',
                fileName: 'error.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 231882,
                fileType: 'application/zip',
              },
              {
                id: 183,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                attachment: '8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                extension: 'zip',
                fileName: '0000.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 2006583,
                fileType: 'application/zip',
              },
            ],
            threadId: 142,
          },
        },
      },
    },
    {
      threadId: 141,
      textCover: false,
      userId: 30,
      categoryId: 12,
      title: '荣耀Play4T手机 【华为手机 店内可选】 极光色 全网通 (6+128G)888',
      price: '0.00',
      attachmentPrice: '0.00',
      isEssence: false,
      user: {
        userId: 30,
        userName: 'a46',
        avatar: 'http://dev.discuz.com/storage/avatars/000/00/00/30.png?1618384809',
        threadCount: 30,
        followCount: 0,
        fansCount: 0,
        likedCount: 8,
        questionCount: 0,
        isRealName: false,
        joinedAt: '2021-04-01 11:21:26',
      },
      group: {
        groupId: 16,
        groupName: '入门会员',
        groupIcon: '',
        isDisplay: true,
      },
      likeReward: {
        users: [],
        likePayCount: 0,
        shareCount: 0,
      },
      position: {
        longitude: '0.0000000',
        latitude: '0.0000000',
        address: '',
        location: '',
      },
      content: {
        text: '去年11月以来，中国海关总署宣布，因从澳大利亚多地进口的原木中检出检疫性有害生物，根据相关法律暂停',
        indexes: {
          $0: {
            tomId: '101',
            operation: 'select',
            body: [
              {
                id: 178,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                attachment: '5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                extension: 'jpg',
                fileName: '12.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 55544,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv_thumb.jpg',
              },
              {
                id: 179,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                attachment: '8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                extension: 'jpg',
                fileName: '14.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 28693,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2_thumb.jpg',
              },
              {
                id: 180,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                attachment: 'FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                extension: 'jpg',
                fileName: '13.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 13760,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l_thumb.jpg',
              },
              {
                id: 181,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                attachment: 'GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                extension: 'jpg',
                fileName: '15.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 37923,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ_thumb.jpg',
              },
            ],
            threadId: 141,
          },
          $1: {
            tomId: '103',
            operation: 'select',
            body: false,
            threadId: 141,
          },
          $2: {
            tomId: '102',
            operation: 'select',
            body: false,
            threadId: 141,
          },
          $3: {
            tomId: '104',
            operation: 'select',
            body: {
              userId: 30,
              platformId: '69777843625',
              title: '卓真 全网通平板电脑11.6英寸10G+128G安卓手机5G学生平板二合一科大讯飞语音学习机Y105 香槟金【10G+128G】+3年质保 全网通+WIFI版',
              imagePath: 'https://m.360buyimg.com/mobilecms/s750x750_jfs/t1/170438/16/18737/492481/607836ffE979ae457/4568e0cda3b32d79.jpg!q80.dpg',
              price: '939.00',
              type: 2,
              typeName: '京东',
              readyContent: 'https://item.jd.com/69777843625.html',
              detailCcontent: 'https://item.m.jd.com/product/69777843625.html',
            },
            threadId: 141,
          },
          $4: {
            tomId: '108',
            operation: 'select',
            body: [
              {
                id: 182,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                attachment: 'NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                extension: 'zip',
                fileName: 'error.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 231882,
                fileType: 'application/zip',
              },
              {
                id: 183,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                attachment: '8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                extension: 'zip',
                fileName: '0000.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 2006583,
                fileType: 'application/zip',
              },
            ],
            threadId: 141,
          },
        },
      },
    },
    {
      threadId: 140,
      textCover: false,
      userId: 30,
      categoryId: 12,
      title: '荣耀Play4T手机 【华为手机 店内可选】 极光色 全网通 (6+128G)888',
      price: '0.00',
      attachmentPrice: '0.00',
      isEssence: false,
      user: {
        userId: 30,
        userName: 'a46',
        avatar: 'http://dev.discuz.com/storage/avatars/000/00/00/30.png?1618384809',
        threadCount: 30,
        followCount: 0,
        fansCount: 0,
        likedCount: 8,
        questionCount: 0,
        isRealName: false,
        joinedAt: '2021-04-01 11:21:26',
      },
      group: {
        groupId: 16,
        groupName: '入门会员',
        groupIcon: '',
        isDisplay: true,
      },
      likeReward: {
        users: [],
        likePayCount: 0,
        shareCount: 0,
      },
      position: {
        longitude: '0.0000000',
        latitude: '0.0000000',
        address: '',
        location: '',
      },
      content: {
        text: '去年11月以来，中国海关总署宣布，因从澳大利亚多地进口的原木中检出检疫性有害生物，根据相关法律暂停',
        indexes: {
          $0: {
            tomId: '101',
            operation: 'select',
            body: [
              {
                id: 178,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                attachment: '5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                extension: 'jpg',
                fileName: '12.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 55544,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv_thumb.jpg',
              },
              {
                id: 179,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                attachment: '8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                extension: 'jpg',
                fileName: '14.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 28693,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2_thumb.jpg',
              },
              {
                id: 180,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                attachment: 'FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                extension: 'jpg',
                fileName: '13.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 13760,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l_thumb.jpg',
              },
              {
                id: 181,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                attachment: 'GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                extension: 'jpg',
                fileName: '15.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 37923,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ_thumb.jpg',
              },
            ],
            threadId: 140,
          },
          $1: {
            tomId: '103',
            operation: 'select',
            body: false,
            threadId: 140,
          },
          $2: {
            tomId: '102',
            operation: 'select',
            body: false,
            threadId: 140,
          },
          $3: {
            tomId: '104',
            operation: 'select',
            body: {
              userId: 30,
              platformId: '69777843625',
              title: '卓真 全网通平板电脑11.6英寸10G+128G安卓手机5G学生平板二合一科大讯飞语音学习机Y105 香槟金【10G+128G】+3年质保 全网通+WIFI版',
              imagePath: 'https://m.360buyimg.com/mobilecms/s750x750_jfs/t1/170438/16/18737/492481/607836ffE979ae457/4568e0cda3b32d79.jpg!q80.dpg',
              price: '939.00',
              type: 2,
              typeName: '京东',
              readyContent: 'https://item.jd.com/69777843625.html',
              detailCcontent: 'https://item.m.jd.com/product/69777843625.html',
            },
            threadId: 140,
          },
          $4: {
            tomId: '108',
            operation: 'select',
            body: [
              {
                id: 182,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                attachment: 'NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                extension: 'zip',
                fileName: 'error.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 231882,
                fileType: 'application/zip',
              },
              {
                id: 183,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                attachment: '8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                extension: 'zip',
                fileName: '0000.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 2006583,
                fileType: 'application/zip',
              },
            ],
            threadId: 140,
          },
        },
      },
    },
    {
      threadId: 139,
      textCover: false,
      userId: 30,
      categoryId: 12,
      title: '荣耀Play4T手机 【华为手机 店内可选】 极光色 全网通 (6+128G)888',
      price: '0.00',
      attachmentPrice: '0.00',
      isEssence: false,
      user: {
        userId: 30,
        userName: 'a46',
        avatar: 'http://dev.discuz.com/storage/avatars/000/00/00/30.png?1618384809',
        threadCount: 30,
        followCount: 0,
        fansCount: 0,
        likedCount: 8,
        questionCount: 0,
        isRealName: false,
        joinedAt: '2021-04-01 11:21:26',
      },
      group: {
        groupId: 16,
        groupName: '入门会员',
        groupIcon: '',
        isDisplay: true,
      },
      likeReward: {
        users: [],
        likePayCount: 0,
        shareCount: 0,
      },
      position: {
        longitude: '0.0000000',
        latitude: '0.0000000',
        address: '',
        location: '',
      },
      content: {
        text: '去年11月以来，中国海关总署宣布，因从澳大利亚多地进口的原木中检出检疫性有害生物，根据相关法律暂停',
        indexes: {
          $0: {
            tomId: '101',
            operation: 'select',
            body: [
              {
                id: 178,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                attachment: '5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                extension: 'jpg',
                fileName: '12.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 55544,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv_thumb.jpg',
              },
              {
                id: 179,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                attachment: '8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                extension: 'jpg',
                fileName: '14.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 28693,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2_thumb.jpg',
              },
              {
                id: 180,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                attachment: 'FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                extension: 'jpg',
                fileName: '13.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 13760,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l_thumb.jpg',
              },
              {
                id: 181,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                attachment: 'GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                extension: 'jpg',
                fileName: '15.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 37923,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ_thumb.jpg',
              },
            ],
            threadId: 139,
          },
          $1: {
            tomId: '103',
            operation: 'select',
            body: false,
            threadId: 139,
          },
          $2: {
            tomId: '102',
            operation: 'select',
            body: false,
            threadId: 139,
          },
          $3: {
            tomId: '104',
            operation: 'select',
            body: {
              userId: 30,
              platformId: '69777843625',
              title: '卓真 全网通平板电脑11.6英寸10G+128G安卓手机5G学生平板二合一科大讯飞语音学习机Y105 香槟金【10G+128G】+3年质保 全网通+WIFI版',
              imagePath: 'https://m.360buyimg.com/mobilecms/s750x750_jfs/t1/170438/16/18737/492481/607836ffE979ae457/4568e0cda3b32d79.jpg!q80.dpg',
              price: '939.00',
              type: 2,
              typeName: '京东',
              readyContent: 'https://item.jd.com/69777843625.html',
              detailCcontent: 'https://item.m.jd.com/product/69777843625.html',
            },
            threadId: 139,
          },
          $4: {
            tomId: '108',
            operation: 'select',
            body: [
              {
                id: 182,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                attachment: 'NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                extension: 'zip',
                fileName: 'error.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 231882,
                fileType: 'application/zip',
              },
              {
                id: 183,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                attachment: '8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                extension: 'zip',
                fileName: '0000.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 2006583,
                fileType: 'application/zip',
              },
            ],
            threadId: 139,
          },
        },
      },
    },
    {
      threadId: 135,
      textCover: false,
      userId: 30,
      categoryId: 12,
      title: '荣耀Play4T手机 【华为手机 店内可选】 极光色 全网通 (6+128G)888',
      price: '0.00',
      attachmentPrice: '0.00',
      isEssence: false,
      user: {
        userId: 30,
        userName: 'a46',
        avatar: 'http://dev.discuz.com/storage/avatars/000/00/00/30.png?1618384809',
        threadCount: 30,
        followCount: 0,
        fansCount: 0,
        likedCount: 8,
        questionCount: 0,
        isRealName: false,
        joinedAt: '2021-04-01 11:21:26',
      },
      group: {
        groupId: 16,
        groupName: '入门会员',
        groupIcon: '',
        isDisplay: true,
      },
      likeReward: {
        users: [],
        likePayCount: 0,
        shareCount: 0,
      },
      position: {
        longitude: '0.0000000',
        latitude: '0.0000000',
        address: '',
        location: '',
      },
      content: {
        text: '去年11月以来，中国海关总署宣布，因从澳大利亚多地进口的原木中检出检疫性有害生物，根据相关法律暂停',
        indexes: {
          $0: {
            tomId: '101',
            operation: 'select',
            body: [
              {
                id: 178,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                attachment: '5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv.jpg',
                extension: 'jpg',
                fileName: '12.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 55544,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/5if1DvaxNUwTsqTfv2lbgDSp4BLMYZeb1sjHu0Cv_thumb.jpg',
              },
              {
                id: 179,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                attachment: '8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2.jpg',
                extension: 'jpg',
                fileName: '14.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 28693,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/8oX57hoIjprerYtThvPGi21J84VOJfSiayG2eXm2_thumb.jpg',
              },
              {
                id: 180,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                attachment: 'FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l.jpg',
                extension: 'jpg',
                fileName: '13.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 13760,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/FnQZpHaGiAv0OFiUp2FMD3DimFyADFgg3w7Mkx7l_thumb.jpg',
              },
              {
                id: 181,
                order: 0,
                type: 1,
                typeId: 133,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                attachment: 'GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ.jpg',
                extension: 'jpg',
                fileName: '15.jpg',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 37923,
                fileType: 'image/jpeg',
                thumbUrl: 'http://dev.discuz.com/storage/attachments/2021/04/16/GBN7Rzl2jvSuGqQ6hKhC1ZcuxSz9rnnebAcvbRnQ_thumb.jpg',
              },
            ],
            threadId: 135,
          },
          $1: {
            tomId: '103',
            operation: 'select',
            body: false,
            threadId: 135,
          },
          $2: {
            tomId: '102',
            operation: 'select',
            body: false,
            threadId: 135,
          },
          $3: {
            tomId: '104',
            operation: 'select',
            body: {
              userId: 30,
              platformId: '69777843625',
              title: '卓真 全网通平板电脑11.6英寸10G+128G安卓手机5G学生平板二合一科大讯飞语音学习机Y105 香槟金【10G+128G】+3年质保 全网通+WIFI版',
              imagePath: 'https://m.360buyimg.com/mobilecms/s750x750_jfs/t1/170438/16/18737/492481/607836ffE979ae457/4568e0cda3b32d79.jpg!q80.dpg',
              price: '939.00',
              type: 2,
              typeName: '京东',
              readyContent: 'https://item.jd.com/69777843625.html',
              detailCcontent: 'https://item.m.jd.com/product/69777843625.html',
            },
            threadId: 135,
          },
          $4: {
            tomId: '108',
            operation: 'select',
            body: [
              {
                id: 182,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                attachment: 'NUoV6UX8zcWcutGvOWOMfEJUqa3xT5CYQ4ROoHNM.zip',
                extension: 'zip',
                fileName: 'error.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 231882,
                fileType: 'application/zip',
              },
              {
                id: 183,
                order: 0,
                type: 0,
                typeId: 161,
                isRemote: false,
                isApproved: 1,
                url: 'http://dev.discuz.com/storage/attachments/2021/04/16/8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                attachment: '8yTmqkDw0hZUfO06MCvTxXWWBJ7fuRUmnoLnAhtR.zip',
                extension: 'zip',
                fileName: '0000.zip',
                filePath: 'public/attachments/2021/04/16/',
                fileSize: 2006583,
                fileType: 'application/zip',
              },
            ],
            threadId: 135,
          },
        },
      },
    },
  ],
  currentPage: 1,
  perPage: 5,
  firstPageUrl: 'http://dev.discuz.com/apiv3/thread.list?sequence=1&perPage=5&page=1',
  nextPageUrl: 'http://dev.discuz.com/apiv3/thread.list?sequence=1&perPage=5&page=2',
  prePageUrl: 'http://dev.discuz.com/apiv3/thread.list?sequence=1&perPage=5&page=1',
  pageLength: 5,
  totalCount: 95,
  totalPage: 19,
};

